# Book settings
title: "Vadar Alpha: Clarity with Data Series"
author: "Vadar Alpha"
logo: "_static/images/logo.png"
copyright: "2024 Vadar Alpha, Inc"

# Configuration for the Jupyter Book
repository:
  url: https://github.com/VadarAlpha/blog-posts
  path_to_book: "https://vadaralpha.github.io/blog-posts/notebooks/index.html"

# Additional settings
html:
  favicon: "_static/images/favicon.ico"

# Execution settings
execution:
  timeout: 1200 # Timeout in seconds (e.g., 600 seconds = 10 minutes)

